### ISSUE TITLE
missing last row of every page in PDF 

### ISSUE THREAD

**Issue by olivercheng6101** [JonathanLink/PDFLayoutTextStripper#11]
hello , thankyou for making this open source 

But i tried to apply the new class and the result is missing last row of every page in PDF

**Comment by olivercheng6101** [comment]
its was fine when i run the programmer without PDFLayoutTextStripper.Class

**Comment by JonathanLink** [comment]
Thank you for reporting that. It is fixed now (see v.2.1)

**Comment by vishnu41** [comment]
I'm facing the same issue. Where can I find v.2.1?
Thank you.
