### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by pnvamshi** [JonathanLink/PDFLayoutTextStripper#16]
If I use JavaSE-1.7 I get error java.lang.IllegalArgumentException: Comparison method violates its general contract! for some PDF documents which I am trying to convert.

If use below versions it works fine. I read online that MergeSort implementation has changed.
This link may help you: https://stackoverflow.com/questions/11441666/java-error-comparison-method-violates-its-general-contract

This method has some problem I guess.
private void sortTextPositionList(final List<TextPosition> textList) {
		TextPositionComparator comparator = new TextPositionComparator();
		Collections.sort(textList, comparator);
	}

**Comment by pnvamshi** [comment]
Found a work around: 
System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");  should be used in the main class or before importing java.util.Arrays in JavaSE-1.6 and above

**Comment by JonathanLink** [comment]
Hello, thanks for your feedback. Can I have the pdf which causes that exception? I cannot reproduce that bug.

**Comment by JonathanLink** [comment]
It's fixed! Thanks again. https://github.com/JonathanLink/PDFLayoutTextStripper/releases/tag/v.2.2.2

**Comment by rivella50** [comment]
Hi Jonathan,
i just ran into the problem again with the latest version 2.3 in dev branch.
PDF document is attached.
Happens with the call
```
(new PDFLayoutTextStripper()).getText(pdDocument);
```
[sheet.pdf](https://github.com/JonathanLink/PDFLayoutTextStripper/files/1625606/sheet.pdf)
