### ISSUE TITLE
Zero height of TextPosition is not handled

### ISSUE THREAD

**Issue by frozen00000** [JonathanLink/PDFLayoutTextStripper#18]
Hi,

I faced case where PDFBox returns 0 as a height of TextPosition in the method "[getNumberOfNewLinesFromPreviousTextPosition](https://github.com/JonathanLink/PDFLayoutTextStripper/blob/c9182615feab58cfa42eda5e2a6a6fb42308e94c/PDFLayoutTextStripper.java#L175)". Not sure why we have such strange height, but it leads to very large loop in the "[createNewEmptyNewLines](https://github.com/JonathanLink/PDFLayoutTextStripper/blob/c9182615feab58cfa42eda5e2a6a6fb42308e94c/PDFLayoutTextStripper.java#L160)" method. If the height of TextPosition is _0_ then we try to divide by _0_ and  _**numberOfLines**_ becomes equal to _Integer.MAX_VALUE_.
I suggest to add a new condition (textPosition.getHeight() != 0) for this case to that [line](https://github.com/JonathanLink/PDFLayoutTextStripper/blob/c9182615feab58cfa42eda5e2a6a6fb42308e94c/PDFLayoutTextStripper.java#L174). Does it make sense? If so then I can a create pull request.

Regards,
Timur

**Comment by rivella50** [comment]
I encounter the same behaviour with some PDFs i need to parse (see attached).
In addition i observe calls for method isSpaceCharacterAtIndex with index values of 0, which leads to java.lang.StringIndexOutOfBoundsException.
[sheet.pdf](https://github.com/JonathanLink/PDFLayoutTextStripper/files/1604181/sheet.pdf)

**Comment by JonathanLink** [comment]
Hello, thanks for reporting! I am going to fix that.

**Comment by JonathanLink** [comment]
@frozen00000  @rivella50 
Is that better?
[https://github.com/JonathanLink/PDFLayoutTextStripper/blob/dev/PDFLayoutTextStripper.java](url)

**Comment by rivella50** [comment]
Runs through now with the sheet i submitted and shows the same parsing results when comparing with the default PDFBox stripper.
Thank you very much, Jonathan!

**Comment by frozen00000** [comment]
Yes, it looks better. Thank you, Jonathan.

**Comment by cricketer** [comment]
Looks like this fix never got merged from dev to master?

**Comment by antsfiles** [comment]
Oh damm, I just saw you fixed it and I did the same. lol
