### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by gunnarmorling** [JonathanLink/PDFLayoutTextStripper#25]
Hi, could you please provide a file with the licensing information in the root directory, so that the applying license is easily apparent and also will correctly linked in the GitHub UI? Thanks.

**Comment by JonathanLink** [comment]
Hello, yes I am going to add the licence as soon as I can.

**Comment by gunnarmorling** [comment]
Thanks; great work btw. with this implementation, I'm successfully using it in native code (via GraalVM) in a small demo here: https://github.com/gunnarmorling/quarkus-pdf-extract 👍

**Comment by JonathanLink** [comment]
License has been added. It's Apache-2.0

**Comment by JonathanLink** [comment]
Glad to see that my work has been reused for this small demo. I didn't know about Quarkus, I am going to have a closer look at it!
