### ISSUE TITLE
Deploy artifact to Maven Central

### ISSUE THREAD

**Issue by gunnarmorling** [JonathanLink/PDFLayoutTextStripper#26]
Hi, could you please provide an artifact with this class on Maven Central, so others can easily use it without having to build it from source? Thanks!

**Comment by JonathanLink** [comment]
Hello, yes I am going to provide an artifact on Maven Central as soon as possible.

**Comment by JonathanLink** [comment]
This has been done as well. It's available here: https://search.maven.org/artifact/io.github.jonathanlink/PDFLayoutTextStripper
The README contains the \<dependency> info

**Comment by gunnarmorling** [comment]
Great news, thanks a lot!

>
