### ISSUE TITLE
will it provide a python wrapper

### ISSUE THREAD

**Issue by loveJasmine** [JonathanLink/PDFLayoutTextStripper#32]

**Comment by vlall** [comment]
It looks like a python wrapper would need to be created.

**Comment by thoqbk** [comment]
I think I can work on this

**Comment by thoqbk** [comment]
@vlall and @loveJasmine I added some code to support Python, can you have a try?
https://github.com/thoqbk/PDFLayoutTextStripper#with-python

**Comment by loveJasmine** [comment]
nice work, thanks
@thoqbk
