### ISSUE TITLE
GitHub release

### ISSUE THREAD

**Issue by baimafeima** [JonathanLink/PDFLayoutTextStripper#6]
Could you release versioned tarballs here on GitHub?

**Comment by JonathanLink** [comment]
Yes, I'll release it in 1 week or so

**Comment by JonathanLink** [comment]
Sorry for the delay. I've released it now.

**Comment by baimafeima** [comment]
mhm, no tagged releases yet?

**Comment by JonathanLink** [comment]
yes https://github.com/JonathanLink/PDFLayoutTextStripper/blob/master/PDFLayoutTextStripper.tar.gz
