### ISSUE TITLE
How to support Chinese character from pdf to txt?

### ISSUE THREAD

**Issue by vincentruan** [JonathanLink/PDFLayoutTextStripper#7]
I have found some solutions by using OCI to identified Chinese character, how to integrate OCI with PDFLayoutTextStripper?
Any reply will be appreciated. Thx

**Comment by JonathanLink** [comment]
You meant OCR? What is the output of your OCR? Is it a pdf with Chinese characters? Which OCR did you use?

**Comment by vincentruan** [comment]
Yes, OCR. And I use the component which is based on **tesseract-ocr**.
I expect the PDF, which contains Chinese character, can be converted as a string, and then I could echo it to a txt file.
The problem is, I found no way to embed a plugin(such as, OCR, etc) for lack of open API ?
Would you provide it, so that I could customize the output stream?
BR and thx?

**Comment by JonathanLink** [comment]
Sorry for the late answer! I am not sure to understand you well. My program takes as input a PDF file and outputs a txt file with more or less the same layout than the input. OCR usually takes as input an image and outputs a txt file, I don't know how they deal with the layout. However I saw that tesseract-ocr give you the option to output a PDF file. If that PDF contains the Chinese characters then you can simply use this file as input of PDFLayoutTextStripper, see the 'How to use' section of the README file.
